## required for packing the npm package with pnpm
nodeLinker: hoisted
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyExclude:
  # required by commit-and-tag-version@12.6.1 and eslint-plugin-import@2.32.0
  - semver@5.7.2 || 6.3.1
  # required by @types/node@20.19.25
  - undici-types@6.21.0
minimumReleaseAge: 10080
onlyBuiltDependencies:
  - "esbuild"
  - "unrs-resolver"
